title: Flutter Developer Talks
email: fluttermiddlepodcast@gmail.com
github_username: fluttermiddlepodcast
domain: flutterdevelopertalks.github.io
url: https://flutterdevelopertalks.github.io

favicon: "favicon.png"

theme: no-style-please
plugins:
  - jekyll-feed

theme_config:
  appearance: "light"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
