title: Flutter Developer Talks
email: fluttermiddlepodcast@gmail.com
github_username: fluttermiddlepodcast
domain: fluttermiddlepodcast.github.io
url: https://fluttermiddlepodcast.github.io
author: Flutter Developer Talks
description: Блог о Flutter-разработке

favicon: "favicon.png"

theme: no-style-please

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
